security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users_in_memory: { memory: null }
        usersproviders:
            #id: usersproviders.user_provider.mail
            entity:
                class: App\Entity\Users
        mairiesproviders:
            #id: usersproviders.user_provider.mail
            entity:
                class: App\Entity\Mairie
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            logout:
                path: logout
            anonymous: true
            lazy: true
            provider: usersproviders


            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/utilisateur/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/utilisateur/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/mairie/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         #- { path: ^/, roles: ROLE_USER }